[project]
name = "gitsymphony"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydub>=0.25.1",
    "typer>=0.15.2",
]
